image: openbsd/latest
tasks:
- get_script: |
    ftp -o -  https://raw.githubusercontent.com/datasetu/datasetu-auth-server/master/install > ftp-script.sh
    sed -i "s/setup/setup test noreboot/" ftp-script.sh
    sed -i "s/syspatch//" ftp-script.sh
- build: |
    doas sh ftp-script.sh
- test: |
    doas pkg_add py-requests py-cryptography py-psycopg2
    cd /home/iudx-auth-server/test
    doas chmod 775 .
    doas chmod 775 ../passwords/auth.db.password
    doas chmod 775 ../rzpay.key.secret
    export AUTH_SERVER='localhost'
    doas /home/iudx-auth-server/test/set-local.sh
    ./run
