#!/bin/sh

export NODE_ENV=production
export TZ=Asia/Kolkata

telegram_apikey=`grep TELEGRAM_APIKEY config-prod.js | grep -v BOT | grep -o "\".*\"," | tr -d '",'`
telegram_chat_id=`grep TELEGRAM_CHAT_ID config-prod.js | grep -o "\".*\"," | tr -d '",'`

id=`id | cut -f1 -d'('`

if [ $id != "uid=0" ]
then
	echo
	echo "===> Usage: sudo $0"
	echo
	exit
fi

NODE_JS_OPTIONS="--zero-fill-buffers --tls-min-v1.0 --tls-min-v1.2" # to support some hardwares 
NODE_JS_OPTIONS="--zero-fill-buffers" 

while :
do
	/usr/local/bin/node $NODE_JS_OPTIONS main.js
	/usr/local/bin/curl "https://api.telegram.org/bot$telegram_apikey/sendMessage?chat_id=$telegram_chat_id&text=[AUTH]:server-crashed"
	sleep 1
	echo "================> Restarting ===================="
done
